# Generated by Django 3.1 on 2020-09-02 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('newslink', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=50)),
                ('keyword', models.CharField(max_length=100)),
                ('press', models.CharField(max_length=10)),
                ('news_num', models.IntegerField()),
            ],
        ),
    ]
